FROM node:18.18.1 as build

ARG FULL_VERSION
ARG IS_ENTERPRISE=FALSE
ARG LOGO_PATH_LIGHT_MODE
ARG LOGO_PATH_DARK_MODE

RUN echo "building $FULL_VERSION"
WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY . .

RUN yarn install
# If this causes problems on github actions: A potential fix is to change the builder image to `node:alpine`
RUN VITE_BASE=/ui/ VITE_IS_ENTERPRISE=${IS_ENTERPRISE} VITE_LOGO_PATH_LIGHT_MODE=${LOGO_PATH_LIGHT_MODE} VITE_LOGO_PATH_DARK_MODE=${LOGO_PATH_DARK_MODE} yarn build

# production environment
FROM nginx:stable-alpine

COPY --from=build /app/dist /usr/share/nginx/html/ui
COPY conf/nginx.dev.conf /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]