name: E2E Playwright local Tests
on: pull_request
env:
  KUBECONFIG: /etc/rancher/k3s/k3s.yaml
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache Playwright browsers
        uses: actions/cache@v2
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-browsers-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-playwright-browsers-
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Cache Node.js dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-
      - name: Install dependencies
        run: yarn
        env:
          CI: true
      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps
      - name: setup k3s
        run: curl -sfL https://get.k3s.io | sh -s - --disable traefik --write-kubeconfig-mode=644
      - name: setup helm
        run: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      - name: install a db
        run: helm repo add bitnami https://charts.bitnami.com/bitnami && helm install psql-single bitnami/postgresql --set postgresqlUsername=direktiv --set postgresqlPassword=direktivdirektiv
      - name: add repo
        run: helm repo add direktiv https://chart.direktiv.io
      - name: install direktiv
        run: helm install direktiv direktiv/direktiv
      - name: Wait for direktiv-flow pod to be ready
        run: |
            while ! kubectl wait --for=condition=Ready pod -l app.kubernetes.io/instance=direktiv --timeout=300s; do sleep 10; done
      - name: Run Playwright tests
        run: yarn playwright test --workers 8
  
        #run: yarn jest
        env:
          VITE_E2E_UI_HOST: 127.0.0.0
          VITE_E2E_UI_PORT: 80
          VITE_DEV_API_DOMAIN: admin
          #VITE_E2E_UI_HOST: ${{ vars.VITE_E2E_UI_HOST }}
          #VITE_E2E_UI_PORT: ${{ vars.VITE_E2E_UI_PORT }}
          #VITE_DEV_API_DOMAIN: ${{ vars.VITE_DEV_API_DOMAIN }}
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
