name: Playwright Tests
on: pull_request
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache Playwright browsers
        uses: actions/cache@v2
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-browsers-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-playwright-browsers-
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn
        env:
          CI: true
      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps
      - name: Run Playwright tests
        run: yarn playwright test --headless
        #run: yarn jest
        env:
          VITE_E2E_UI_HOST: ${{ vars.VITE_E2E_UI_HOST }}
          VITE_E2E_UI_PORT: ${{ vars.VITE_E2E_UI_PORT }}
          VITE_DEV_API_DOMAIN: ${{ vars.VITE_DEV_API_DOMAIN }}
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
