name: Playwright Tests
on: pull_request
jobs:
  test:
    timeout-minutes: 60
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn
      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps
      - name: Run Playwright tests
        run: yarn playwright test
        env:
          VITE_E2E_UI_HOST: ${{ vars.VITE_E2E_UI_HOST }}
          VITE_E2E_UI_PORT: ${{ vars.VITE_E2E_UI_PORT }}
          VITE_DEV_API_DOMAIN: ${{ vars.VITE_DEV_API_DOMAIN }}
          VITE_E2E_API_TOKEN: ${{ vars.VITE_E2E_API_TOKEN }}
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
