name: "Publish Storybook to Chromatic"
on:
  push:
    branches: [ "feature/redesign" ]
jobs:
  build:
    name: Build and test design system
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # chromatic needs all commits
      - name: Install dependencies
        run: yarn
        env:
          CI: true
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          buildScriptName: storybook:build
