name: Make test build
on:
  push:
    branches-ignore:
      - 'main'
jobs:
  build:
    name: Make build and run testsuite
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-
      - name: run linter, typecheck, prettier and make testbuild
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install -g yarn
      - run: yarn install
      # build will automatically run prebuild
      - run: yarn build
